// Do not edit this file, it exists to provide an entry point to subsequent sections and exercises
import { Stack } from "expo-router";

export default function ExercisesLayout() {
  return (
    <Stack>
      <Stack.Screen name="index" options={{ headerShown: false }} />
      <Stack.Screen name="alerts" options={{ headerShown: false }} />
      <Stack.Screen name="styling" options={{ headerShown: false }} />
    </Stack>
  );
}
